# Generated by Django 3.2.8 on 2021-10-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_added',
        ),
        migrations.AddField(
            model_name='note',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
